#7 - CVE : removed unused dependency causing CVE warning.
exasol/db-fundamentals-java pull request #8
Opened 2021-07-05 08:19 UTC by pj-spoelders

Closes #7 
Removed unused dependency

2021-07-05 14:02 UTC, jakobbraun commented
Please add a note to the changelog

2021-07-05 14:03 UTC, jakobbraun commented
And also increase the version number

2021-07-06 08:54 UTC, jakobbraun requested changes

2021-07-06 08:54 UTC, jakobbraun commented on doc/changes/changes_0.1.2.md
> +# Exasol Database fundamentals for Java 0.1.2, released 05.07.2021
```suggestion
# Exasol Database fundamentals for Java 0.1.2, released 2021-07-06
```

2021-07-06 08:54 UTC, jakobbraun commented on doc/changes/changes_0.1.2.md
> +Code name:
Add a name for the release

2021-07-06 08:54 UTC, jakobbraun commented on pom.xml
> +                        <!-- add modules here: -->
```suggestion
```

2021-07-06 09:05 UTC, pj-spoelders commented on doc/changes/changes_0.1.2.md
> +Code name:
done

2021-07-06 09:07 UTC, jakobbraun approved these changes

2021-07-06 10:45 UTC, merged